name: Lint JSON and YML

on: [push]

permissions:
  contents: read

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run prettier
